### ISSUE TITLE
When run bridge.py

### ISSUE THREAD

**Issue by YuanbinCN** [MaisJamal/carla_apollo_bridge#19]
I followed the steps in the instructions.

Apollo 8.0, carla 0.9.13, and this repository can be built.

Carla server can run, dream view can also launched.

But when I run  "python carla_cyber_bridge/run_bridge.py", I got this:

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0907 05:42:19.890605   871 cyber_time_wrap.cc:338] [] init _cyber_time
I0907 05:42:19.902513   871 cyber_timer_wrap.cc:164] [] init _cyber_timer
Traceback (most recent call last):
  File "carla_cyber_bridge/run_bridge.py", line 366, in <module>
    main()
  File "carla_cyber_bridge/run_bridge.py", line 345, in main
    camera = carla_world.get_actors().filter('sensor.camera.rgb')[0]
IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Can you give any hints on how to solve this problem? Thanks

**Comment by teiseong** [comment]
I already met this issue once. What I did is restarted Carla, and tried that bridge script again and again until it worked.

**Comment by MaisJamal** [comment]
This issue happens when you run the bridge "bridge.py" before running Carla scenario. That's why it shows that no sensor and no actor are found. Make sure always to run a Carla scenario, for example "manual_control.py", before running the bridge as it depends on it.
In future I will fix this issue.
